apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudshelf-web
  namespace: cloudshelf-namespace

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloudshelf-web

  template:
    metadata:
      labels:
        app: cloudshelf-web

    spec:
      containers:
        - name: nginx
          image: nginx:1.27

          ports:
            - containerPort: 80

          volumeMounts:
            - name: website-content
              mountPath: /usr/share/nginx/html
              readOnly: true

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

      volumes:
        - name: website-content
          configMap:
            name: website-config
